const trans = {
	en: {
		services: "Services",
		// what: "What we",
		how: "How we",
		carreers: "carreers",
		about: "about us",
		contact: "contact us",
		estimate: "estimate your project",
		save1: "save up to ",
		save2: "30%",
		save3: "of your cost.",
		project1: "project starts at",
		project2: "14",
		project3: "days guarenteed.",
		technologies1: "with the best",
		technologies2: "technologies.",
		tissenWay: "Tissen Way",
		innovativeSolutions1: "Expertise and ",
		innovativeSolutions2: "innovative solutions.",
		personalizedApproach1: "Personalized approach ",
		personalizedApproach2: "tailored to specific needs.",
		successfulImplementations1: "Proven track record of ",
		successfulImplementations2: "successful implementations.",
		comprehensivePortfolio1: "Comprehensive portfolio ",
		comprehensivePortfolio2: "of services for various technological needs.",
		customerRelationships1: "Consumer-centric approach and ",
		customerRelationships2: "strong customer relationships.",
		byServices: "By Services",
		softwareDevelopment: "Software Development",
		seguridadInformatica: "Network Security",
		cloudHosting: "Cloud Hosting",
		desarrolloWeb: "Web Development ",
		desarrolloMobile: "Mobile Develompent",
		byTechnologie: "By Technologie",
		IT_Outsourcing: "IT outsourcing offers cost reduction, access to specialized skills, focus on core competencies, scalability, improved service levels and risk mitigation.",
		whereAreWe: "Where are we",
		theTissen: "The Tissen IT company provides technology services and solutions, specializing in software development and IT consulting. We employ qualified professionals and offer outsourcing services globally, contributing to the growth of the IT industry in South America.",
		southAmerica: "South America",
		GermanIT: "A German IT company providing assistance in the USA specializes in delivering a wide range of IT services and solutions tailored to meet the specific needs of American businesses. With its technical expertise, innovative approach, and cross-cultural understanding, it helps optimize IT operations.",
		northAmerica: "North America",
		weAre: "We are a German IT outsourcing company in Europe providing businesses with cost-effective and efficient IT solutions and services. We help companies streamline their IT operations while allowing them to focus on their core competencies.",
		europe: "Europe",
		// Footer
		footerServices: "Services",
		footerSoftware: "Software Development",
		footerSecurity: "Network Security",
		footerCloud: "Cloud Hosting ",
		footerWeb: "Web Development",
		footerMobile: "Mobile Development",
		footerTechnologies: "Technologies",
		footerCompany: "Company",
		footerAbout: "About us",
		footerCarrers: "Carrers",
		footerWhy: "Why us",
		footerHow: "How us ",
		footerContact: "Contact us",
		footerEmail: "Email",
		footerPhone: "Phones",
		// Services
		servicesRouter: "Services",
		servicesSoftwareDevelopmentTitle: "Software Development",
		servicesSoftwareDevelopmentText: "Transform your ideas into reality with our custom software development services. Our expert developers will create tailored solutions that align with your business goals, delivering high-quality code and seamless user experiences.",
		servicesWebDevelpomentTitle: "Web Development",
		servicesWebDevelpomentText: "Transform your ideas into reality with our custom software development services. Our expert developers will create tailored solutions that align with your business goals, delivering high-quality code and seamless user experiences.",
		servicesMobileDevelopmentTitle: "Mobile Development",
		servicesMobileDevelopmentText: "Reach your target audience on their preferred devices with our mobile development services. We specialize in building intuitive and feature-rich mobile applications for both iOS and Android platforms.",
		servicesNetworkSecuretyTitle: "Network Security",
		servicesNetworkSecuretyText: "Ensure the safety of your data and network infrastructure with our comprehensive network security services. We offer risk assessments, intrusion detection, firewall implementation, and ongoing monitoring to protect your valuable information from potential threats.",
		servicesCloudHostingTitle: "Cloud Hosting",
		servicesCloudHostingText: "Experience the benefits of flexible and reliable cloud hosting. Our experts will guide you through a seamless migration process, optimizing performance and reducing the burden of managing physical servers.",
		servicesUXTitle: "UX/UI",
		servicesUXText: "Deliver exceptional user experiences with our UX/UI design services. Our designers combine aesthetics, usability, and functionality to create interfaces that engage users and drive customer satisfaction.",
		servicesWorkingProcessTitle: "Tissen Working Process",
		servicesRequermentsTitle: "Requirements Gathering",
		servicesRequermentsText: "Gathering and analyzing the project requirements, understanding the objectives, and defining the scope of the project.",
		servicesSystemDesignTitle: "System Design",
		servicesSystemDesignText: "Creating a detailed system design that outlines the architecture, components, and functionalities of the IT solution.",
		servicesDevelopmentTitle: "Development",
		servicesDevelopmentText: "Writing the code and implementing the system design, using the chosen programming languages, frameworks, and tools.",
		servicesTestingTitle: "Testing",
		servicesTestingText: "Conducting various testing activities, such as unit testing, integration testing, and system testing, to identify and fix any bugs or issues.",
		servicesDeploymentTitle: "Deployment",
		servicesDeploymentText: "Deploying the developed software or system to the production environment or making it available to users.",
		servicesMaintenenceTitle: "Maintenance and Support",
		servicesMaintenenceText: "Providing ongoing maintenance and support for the developed IT solution, including bug fixes, updates, and user assistance.",
		servicesDocumentationTitle: "Documentation",
		servicesDocumentationText: "Documenting the system, code, and user manuals to ensure proper understanding, maintenance, and future enhancements.",
		servicesContinuousTitle: "Continuous Improvement",
		servicesContinuousText: "Continuously monitoring and evaluating the IT solution's performance, gathering feedback, and making improvements to enhance its functionality and efficiency.",
		servicesExcellenceInServiceTitle: "Excellence in service, exceeding expectations every time.",
		servicesLetsMeet:"LETS MEET",
		// HOW WE
		howTitle: "How we",
		howStepsTitle: "Steps",
		howRequirementsGatheringTitle: "Requirements Gathering",
		howRequirementsGatheringText: "Gathering and analyzing the project requirements, understanding the objectives, and defining the scope of the project.",
		howSystemDesignTitle: "System Design",
		howSystemDesignText: "Creating a detailed system design that outlines the architecture, components, and functionalities of the IT solution.",
		howDevelopmentTitle: "Development",
		howDevelopmentText: "Writing the code and implementing the system design, using the chosen programming languages, frameworks, and tools.",
		howTestingTitle: "Testing",
		howTestingText: "Conducting various testing activities, such as unit testing, integration testing, and system testing, to identify and fix any bugs or issues.",
		howDeploymentTitle: "Deployment",
		howDeploymentText: "Deploying the developed software or system to the production environment or making it available to users.",
		howMaintenanceSupportTitle: "Maintenance and Support",
		howMaintenanceSupportText: "Providing ongoing maintenance and support for the developed IT solution, including bug fixes, updates, and user assistance.",
		howDocumentationTitle: "Documentation",
		howDocumentationText: "Documenting the system, code, and user manuals to ensure proper understanding, maintenance, and future enhancements.",
		howContinuousImprovementTitle: "Continuous Improvement",
		howContinuousImprovementText: "Continuously monitoring and evaluating the IT solution's performance, gathering feedback, and making improvements to enhance its functionality and efficiency.",
		howKnowUs: "KNOW US",
		howAccording: "According to a survey by Deloitte, approximately ",
		howAccording53: "53%",
		howOrganizations: "of organizations worldwide",
		howOutsource: "outsource some or all of their IT functions.",
		howSourceDeloitte: "(Source: Deloitte Global Outsourcing Survey)",
		howInAddition: "In addition to technical skills, employers also value soft skills in IT professionals. ",
		howCommunication: " Communication, problem-solving, teamwork, ",
		howAnd: "and ",
		howAdaptability: "adaptability ",
		howAmong: "are among the essential soft skills sought after by employers.",
		howAdvantagesTitle: "Advantages",
		howCostSavingsTitle: "Cost Savings",
		howCostSavingsText: "We  lead to significant cost savings for businesses. It eliminates the need for hiring and training in-house IT staff, investing in infrastructure, and maintaining technology resources. Outsourcing providers often offer flexible pricing models that allow businesses to pay for services as needed.",
		howCoreBusinessTitle: "Core Business",
		howCoreBusinessText: "Outsourcing IT tasks allows businesses to focus on their core competencies and strategic objectives. By delegating IT responsibilities to external experts, companies can allocate more time and resources to activities that directly contribute to their growth and competitive advantage.",
		howRiskManagementTitle: "Risk Management",
		howRiskManagementText: "We help mitigate risks associated with technology investments and management. Outsourcing providers typically have robust security measures, disaster recovery plans, and compliance frameworks in place, reducing the risk of data breaches, system failures, or regulatory non-compliance.",
		howSpecializedSkillsTitle: "Specialized Skills and Expertise",
		howSpecializedSkillsText: " Tissen provides access to a pool of highly skilled professionals with specialized expertise. Outsourcing providers often have teams of professionals experienced in various technologies and industry best practices. This allows businesses to leverage the knowledge and skills of experts without the need for internal training or recruitment.",
		howScalabilityFlexibilityTitle: "Scalability and Flexibility",
		howScalabilityFlexibilityText: "Working with us provides scalability and flexibility to meet changing business needs. Businesses can easily scale up or down their IT resources based on demand, without the need for extensive infrastructure investments or long-term commitments.",
		howServiceLevelsTitle: "Service Levels",
		howServiceLevelsText: "Outsourcing IT services often comes with defined service level agreements (SLAs) that guarantee a certain level of performance and responsiveness. Providers focus on meeting or exceeding these SLAs, ensuring efficient and reliable IT operations for the business.",
		howThePrimaryText: "The primary reasons organizations choose to outsource IT functions include",
		howCostReduction: " cost reduction",
		how64: " (64%), ",
		howAccessing: "accessing specialized skills ",
		how51: "(51%), ",
		howImproving: "improving focus on core business ",
		how46and: "(46%), and ",
		howEnhancing: "enhancing service quality ",
		how34Source: "(34%). (Source: Deloitte Global Outsourcing Survey)",
		// CARREERS
		carreersJoinOurTeamTitle:"Join Our Team",
		carreersJoinOurTeamText:"Passionate about technology and looking for exciting career opportunities? At Tissen, we're a leading IT outsourcing company offering a range of rewarding roles. Join our team of experts dedicated to solving complex business challenges with talent and innovation.",
		carreersWhyChooseUsTitle:"Why Choose Us?",
		carreersDiverseProjectsTitle:"Diverse Projects",
		carreersDiverseProjectsText:"Work on a variety of projects across industries, from cutting-edge software solutions to large-scale infrastructure deployments. Enhance your skills and expertise with diverse challenges.",
		carreersCompetitiveCompensationTitle:"Competitive Compensation",
		carreersCompetitiveCompensationText:"Enjoy competitive salaries and comprehensive benefits as recognition for your hard work and dedication.",
		carreersWorkLifeBalanceTitle:"Work-Life Balance",
		carreersWorkLifeBalanceText:"We offer flexible schedules and remote work options, ensuring a healthy work-life balance.",
		carreersCollaborativeEnvironmentTitle:"Collaborative Environment",
		carreersCollaborativeEnvironmentText:"Join talented professionals who value teamwork, knowledge-sharing, and an inclusive work culture that fosters creativity and innovation.",
		carreersContinuousLearningTitle:"Continuous Learning",
		carreersContinuousLearningText:"Access training programs, certifications, and industry conferences to stay updated with the latest trends and technologies. We invest in your development.",
		carreersWhatWeWelcomeTitle:"What we welcome",
		carreersExpertiseTitle:"Expertise",
		carreersExpertiseText:"We value strong technical skills in areas like software development, cybersecurity, cloud computing, and more. Show us your expertise and ability to deliver high-quality results.",
		carreersProblemSolvingTitle:"Problem-Solving",
		carreersProblemSolvingText:"We seek individuals who excel at analyzing and solving complex problems. Your critical thinking and innovative solutions will be highly valued.",
		carreersTeamPlayerTitle:"Team Player",
		carreersTeamPlayerText:"Collaboration is key. We want team players who contribute ideas and work seamlessly with colleagues and clients to achieve common goals.",
		carreersAdaptabilityTitle:"Adaptability",
		carreersAdaptabilityText:"The IT industry evolves rapidly, so we need professionals who embrace change and eagerly learn new technologies.",
		carreersStrongCommunicationTitle:"Strong Communication",
		carreersStrongCommunicationText:" Effective communication is vital. We value clear articulation, active listening, and the ability to communicate technical concepts to diverse audiences.",
		carreersClientFocusTitle:"Client Focus",
		carreersClientFocusText:"Our clients' satisfaction is paramount. We seek individuals who understand their needs and are committed to delivering exceptional experiences.",
		carreersDriveExcellenceTitle:"Drive for Excellence",
		carreersDriveExcellenceText:"We strive for excellence. If you have a strong work ethic, attention to detail, and a desire to continuously improve, you'll be a great fit.",
		carreersEntrepreneurialMindsetTitle:"Entrepreneurial Mindset",
		carreersEntrepreneurialMindsetText:"We value proactive individuals with an entrepreneurial mindset. If you're resourceful, take ownership, and drive business growth, join our team. Embrace challenges and make a significant impact on our success.",
		carreersStrongerTogether:"Stronger Together, Achieving Greatness as One Team.",
		carreersDoYouHave:"Do you have something else to contribute?",
		carreersLetsTalk:"Lets talk",
		// ABOUT US
		aboutTitle:"About",
		aboutOurMissionTitle:"Our mission",
		aboutOurMissionText:"Our mission at Tissen is to empower businesses by harnessing the transformative power of technology. We strive to deliver quality IT solutions that drive success, whether through innovative software development, efficient IT infrastructure management or strong data security measures. By adhering to industry best practices, utilizing the latest technologies and working closely with our clients, we gain a deep understanding of their goals and challenges. This enables us to deliver tailor-made solutions that move your business forward.",
		aboutOurMissionText2:"Tissen is a leading IT outsourcing company headquartered in Argentina serving clients worldwide. With our team of highly skilled professionals and industry experts, we focus on delivering superior outsourcing solutions to meet our clients' unique business needs. We distinguish ourselves through an unwavering commitment to excellence, transparent communication and building lasting partnerships based on trust, reliability and mutual growth.",
		aboutOurVisionTitle:"Our Vision",
		aboutOurVisionText:"Our vision is to be the first choice for companies looking for a reliable and competent IT outsourcing partner. We strive to be recognized for our expertise, unwavering reliability and unwavering commitment to customer satisfaction. With a diverse portfolio of successful projects across multiple industries, we strive to position ourselves as trusted advisors helping companies realize their full potential through technology. Through our unwavering commitment and utilizing Argentina's exceptional talent pool, we aim to consistently deliver exceptional results, giving our clients a competitive advantage in their markets.",
		aboutEmpowering:"Empowering Technology, Supporting Users",
		aboutLetsMeet:"Lets meet",
		aboutWorkingTitle:"Tissen Working Staff",
		aboutWorkingText:"With our IT outsourcing services, you can reduce costs significantly while gaining access to a team of skilled professionals who stay ahead of the latest trends and best practices. We provide round-the-clock support, ensuring your systems run smoothly and addressing issues before they impact your operations.",
		aboutWorkingText2:"Our flexible and scalable services adapt to your evolving needs, and we prioritize security and compliance, safeguarding your data and meeting industry standards. By partnering with us, you can focus on your core business objectives while we handle your IT needs.",
		


	},
	es: {
		services: "Servicios",
		// what: "Que hacemos",
		how: "Como lo hacemos",
		carreers: "Unite",
		about: "nosotros",
		contact: "Contactanos",
		estimate: "Estima tu proyecto",
		save1: "Ahorra hasta un",
		save2: " 30%.",
		save3: "",
		project1: "Proyecto empieza en",
		project2: "14",
		project3: "dias garantizado.",
		technologies1: "Con la mejor",
		technologies2: "Tecnologia",
		tissenWay: "Tissen estilo",
		innovativeSolutions1: "Pericia y ",
		innovativeSolutions2: "soluciones innovadoras.",
		personalizedApproach1: "Enfoque personalizado",
		personalizedApproach2: "adaptado a las necesidades específicas.",
		successfulImplementations1: "Historial comprobado de ",
		successfulImplementations2: "implementaciones exitosas.",
		comprehensivePortfolio1: "Portafolio integral de servicios ",
		comprehensivePortfolio2: "para diversas necesidades tecnológicas.",
		customerRelationships1: "Enfoque centrado en el consumidor y ",
		customerRelationships2: "relaciones sólidas con los clientes.",
		byServices: "Por Servicio",
		softwareDevelopment: "Desarrollo Software ",
		seguridadInformatica: "Seguridad Informatica",
		cloudHosting: "Cloud Hosting",
		desarrolloWeb: "Desarrollo Web ",
		desarrolloMobile: "Desarrollo Mobile",
		byTechnologie: "Por Tecnologia",
		IT_Outsourcing: "La tercerizacion de TI ofrece disminución de costos, acceso a habilidades especializadas, enfoque en competencias básicas, escalabilidad, niveles de servicio mejorados y mitigación de riesgos.",
		whereAreWe: "Donde Estamos",
		theTissen: "La empresa Tissen IT brinda servicios y soluciones de tecnología, especializándose en desarrollo de software y consultoría de TI. Emplean a profesionales calificados y ofrecen servicios de tercerización a nivel mundial, lo que contribuye al crecimiento de la industria de TI en América del Sur.",
		southAmerica: "Sudamerica",
		GermanIT: "Una empresa alemana de TI que brinda asistencia en los EE. UU. se especializa en brindar una amplia gama de servicio. Con su experiencia técnica, enfoque innovador y comprensión intercultural, ayudan a optimizar las operaciones de TI",
		northAmerica: "Norteamerica",
		weAre: "Somos una empresa alemana de subcontratación de TI en Europa que brinda a las empresas servicios y soluciones de TI rentables y eficientes. ayudamos a las empresas a optimizar sus operaciones de TI mientras les permitimos concentrarse en sus competencias principales.",
		europe: "Europa",
		// Footer
		footerServices: "Servicios",
		footerSoftware: "Desarrollo de Software",
		footerSecurity: "Seguridad informatica",
		footerCloud: "Cloud Hosting ",
		footerWeb: "Desarrollo Web",
		footerMobile: "Desarrollo Mobile",
		footerTechnologies: "Tecnologias",
		footerCompany: "Compania",
		footerAbout: "Sobre nosotros",
		footerCarrers: "Unite",
		footerWhy: "Porque Tissen",
		footerHow: "Como Tissen",
		footerContact: "Contactanos",
		footerEmail: "Mail",
		footerPhone: "Telefonos",
		// Services
		servicesRouter: "Servicios",
		servicesSoftwareDevelopmentTitle: "Desarrollo de software",
		servicesSoftwareDevelopmentText: "Transforma tus ideas en realidad con nuestros servicios de desarrollo de software a medida. Nuestros desarrolladores expertos crearán soluciones personalizadas que se alineen con sus objetivos comerciales, brindando código de alta calidad y experiencias de usuario perfectas.",
		servicesWebDevelpomentTitle: "Desarrollo web",
		servicesWebDevelpomentText: "Cree una presencia web cautivadora con nuestros servicios de desarrollo web. Diseñamos y desarrollamos sitios web visualmente atractivos y funcionales que reflejan la identidad de su marca y generan conversiones.",
		servicesMobileDevelopmentTitle: "Desarrollo móvil",
		servicesMobileDevelopmentText: "Llegue a su público objetivo en sus dispositivos preferidos con nuestros servicios de desarrollo móvil. Nos especializamos en la creación de aplicaciones móviles intuitivas y ricas en funciones para las plataformas iOS y Android.",
		servicesNetworkSecuretyTitle: "Seguridad de red",
		servicesNetworkSecuretyText: "Garantice la seguridad de sus datos e infraestructura de red con nuestros completos servicios de seguridad de red. Ofrecemos evaluaciones de riesgo, detección de intrusos, implementación de firewall y monitoreo continuo para proteger su valiosa información de posibles amenazas.",
		servicesCloudHostingTitle: "Alojamiento en la nube",
		servicesCloudHostingText: "Experimente los beneficios de un alojamiento en la nube flexible y confiable. Nuestros expertos lo guiarán a través de un proceso de migración sin problemas, optimizando el rendimiento y reduciendo la carga de administrar servidores físicos.",
		servicesUXTitle: "UX/UI",
		servicesUXText: "Ofrezca experiencias de usuario excepcionales con nuestros servicios de diseño de UX/UI. Nuestros diseñadores combinan estética, facilidad de uso y funcionalidad para crear interfaces que atraigan a los usuarios e impulsen la satisfacción del cliente.",
		servicesWorkingProcessTitle: "Proceso de trabajo Tissen",
		servicesRequermentsTitle: "Recopilación de requisitos",
		servicesRequermentsText: "Recopilación y análisis de los requisitos del proyecto, comprensión de los objetivos y definición del alcance del proyecto.",
		servicesSystemDesignTitle: "System Design",
		servicesSystemDesignText: "Crear un diseño de sistema detallado que describa la arquitectura, los componentes y las funcionalidades de la solución de TI.",
		servicesDevelopmentTitle: "Desarrollo",
		servicesDevelopmentText: "Escribir el código e implementar el diseño del sistema, utilizando los lenguajes de programación, marcos y herramientas elegidos.",
		servicesTestingTitle: "Pruebas",
		servicesTestingText: "Llevar a cabo diversas actividades de prueba, como pruebas unitarias, pruebas de integración y pruebas del sistema, para identificar y corregir cualquier error o problema.",
		servicesDeploymentTitle: "Despliegue",
		servicesDeploymentText: "Implementar el software o sistema desarrollado en el entorno de producción o ponerlo a disposición de los usuarios.",
		servicesMaintenenceTitle: "Mantenimiento y soporte",
		servicesMaintenenceText: "Brindar mantenimiento y soporte continuos para la solución de TI desarrollada, incluidas correcciones de errores, actualizaciones y asistencia al usuario.",
		servicesDocumentationTitle: "Documentation",
		servicesDocumentationText: "Documentar el sistema, el código y los manuales de usuario para garantizar la comprensión, el mantenimiento y las mejoras futuras adecuados.",
		servicesContinuousTitle: "Mejora continua",
		servicesContinuousText: "Supervisar y evaluar continuamente el rendimiento de la solución de TI, recopilar comentarios y realizar mejoras para mejorar su funcionalidad y eficiencia.",
		servicesExcellenceInServiceTitle: "Excelencia en el servicio, superando siempre las expectativas.",
		servicesLetsMeet:"vamos a conocernos",
		// HOW WE
		howTitle: "Como lo hacemos",
		howStepsTitle: "Pasos",
		howRequirementsGatheringTitle: "Recopilación de requisitos",
		howRequirementsGatheringText: "Recopilación y análisis de los requisitos del proyecto, comprensión de los objetivos y definición del alcance del proyecto.",
		howSystemDesignTitle: "Diseño de sistemas",
		howSystemDesignText: "Crear un diseño de sistema detallado que describa la arquitectura, los componentes y las funcionalidades de la solución de TI.",
		howDevelopmentTitle: "Desarrollo",
		howDevelopmentText: "Escribir el código e implementar el diseño del sistema, utilizando los lenguajes de programación, marcos y herramientas elegidos.",
		howTestingTitle: "Pruebas",
		howTestingText: "Llevar a cabo diversas actividades de prueba, como pruebas unitarias, pruebas de integración y pruebas del sistema, para identificar y corregir cualquier error o problema.",
		howDeploymentTitle: "Despliegue",
		howDeploymentText: "Implementar el software o sistema desarrollado en el entorno de producción o ponerlo a disposición de los usuarios.",
		howMaintenanceSupportTitle: "Mantenimiento y soporte",
		howMaintenanceSupportText: "Brindar mantenimiento y soporte continuos para la solución de TI desarrollada, incluidas correcciones de errores, actualizaciones y asistencia al usuario.",
		howDocumentationTitle: "Documentación",
		howDocumentationText: "Documentar el sistema, el código y los manuales de usuario para garantizar la comprensión, el mantenimiento y las mejoras futuras adecuados.",
		howContinuousImprovementTitle: "Mejora continua",
		howContinuousImprovementText: "Supervisar y evaluar continuamente el rendimiento de la solución de TI, recopilar comentarios y realizar mejoras para mejorar su funcionalidad y eficiencia.",
		howKnowUs: "Conocenos",
		howAccording: "Según una encuesta realizada por Deloitte, aproximadamente el ",
		howAccording53: "53%",
		howOrganizations: "de las organizaciones en todo",
		howOutsource: "el mundo subcontratan algunas o todas sus funciones de TI. ",
		howSourceDeloitte: "(Fuente: Encuesta Global de Subcontratación de Deloitte)",
		howInAddition: "Además de las habilidades técnicas, los empleadores también valoran las habilidades blandas en los profesionales de TI.",
		howCommunication: " La comunicación, la resolución de problemas, el trabajo en equipo ",
		howAnd: "y ",
		howAdaptability: "la adaptabilidad ",
		howAmong: "se encuentran entre las habilidades blandas esenciales que buscan los empleadores.",
		howAdvantagesTitle: "Ventajas",
		howCostSavingsTitle: "Ahorro de costes",
		howCostSavingsText: "Conducimos a importantes ahorros de costes para las empresas. Elimina la necesidad de contratar y capacitar personal de TI interno, invertir en infraestructura y mantener los recursos tecnológicos. Los proveedores de subcontratación a menudo ofrecen modelos de precios flexibles que permiten a las empresas pagar los servicios según sea necesario.",
		howCoreBusinessTitle: "negocio principal",
		howCoreBusinessText: "La externalización de tareas de TI permite a las empresas centrarse en sus competencias básicas y objetivos estratégicos. Al delegar responsabilidades de TI a expertos externos, las empresas pueden asignar más tiempo y recursos a actividades que contribuyen directamente a su crecimiento y ventaja competitiva.",
		howRiskManagementTitle: "Gestión de riesgos",
		howRiskManagementText: "Ayudamos a mitigar los riesgos asociados con las inversiones y la gestión de tecnología. Los proveedores de outsourcing suelen tener medidas de seguridad sólidas, planes de recuperación ante desastres y marcos de cumplimiento, lo que reduce el riesgo de violaciones de datos, fallas del sistema o incumplimiento normativo.",
		howSpecializedSkillsTitle: "Habilidades y experiencia especializadas",
		howSpecializedSkillsText: "Tissen brinda acceso a un grupo de profesionales altamente calificados con experiencia especializada. Los proveedores de outsourcing suelen tener equipos de profesionales con experiencia en diversas tecnologías y mejores prácticas de la industria. Esto permite a las empresas aprovechar el conocimiento y las habilidades de los expertos sin necesidad de capacitación o contratación interna.",
		howScalabilityFlexibilityTitle: "Escalabilidad y flexibilidad",
		howScalabilityFlexibilityText: "Trabajar con nosotros proporciona escalabilidad y flexibilidad para satisfacer las cambiantes necesidades comerciales. Las empresas pueden ampliar o reducir fácilmente sus recursos de TI en función de la demanda, sin necesidad de grandes inversiones en infraestructura ni compromisos a largo plazo.",
		howServiceLevelsTitle: "Niveles de servicio",
		howServiceLevelsText: "La subcontratación de servicios de TI a menudo viene con acuerdos de nivel de servicio (SLA) definidos que garantizan un cierto nivel de rendimiento y capacidad de respuesta. Los proveedores se enfocan en cumplir o superar estos SLA, asegurando operaciones de TI eficientes y confiables para el negocio.",
		howThePrimaryText: "Las razones principales por las que las organizaciones optan por subcontratar las funciones de TI incluyen la ",
		howCostReduction: "reducción de costos",
		how64: "(64 %), ",
		howAccessing: "el acceso a habilidades especializadas",
		how51: " (51 %), ",
		howImproving: "mejorar el enfoque en el negocio principal",
		how46and: " (46 %) y ",
		howEnhancing: "mejorar la calidad del servicio ",
		how34Source: "(34 %). (Fuente: Encuesta Global de Subcontratación de Deloitte)",
		// CARREERS
		carreersJoinOurTeamTitle:"Sumate a nuestro equipo",
		carreersJoinOurTeamText:"¿Te apasiona la tecnología y buscas emocionantes oportunidades profesionales? En Tissen, somos una empresa líder en subcontratación de TI que ofrece una variedad de funciones gratificantes. Únase a nuestro equipo de expertos dedicados a resolver desafíos empresariales complejos con talento e innovación.",
		carreersWhyChooseUsTitle:"¿Por qué elegirnos?",
		carreersDiverseProjectsTitle:"Proyectos Diversos",
		carreersDiverseProjectsText:"Trabaje en una variedad de proyectos en todas las industrias, desde soluciones de software de vanguardia hasta implementaciones de infraestructura a gran escala. Mejore sus habilidades y experiencia con diversos desafíos.",
		carreersCompetitiveCompensationTitle:"Compensación Competitiva",
		carreersCompetitiveCompensationText:"Disfrute de salarios competitivos y beneficios integrales como reconocimiento a su arduo trabajo y dedicación.",
		carreersWorkLifeBalanceTitle:"Equilibrio trabajo-vida",
		carreersWorkLifeBalanceText:"Ofrecemos horarios flexibles y opciones de trabajo remoto, asegurando un equilibrio saludable entre el trabajo y la vida.",
		carreersCollaborativeEnvironmentTitle:"Entorno colaborativo",
		carreersCollaborativeEnvironmentText:"Únase a profesionales talentosos que valoran el trabajo en equipo, el intercambio de conocimientos y una cultura laboral inclusiva que fomenta la creatividad y la innovación.",
		carreersContinuousLearningTitle:"Aprendizaje continuo",
		carreersContinuousLearningText:"Acceda a programas de capacitación, certificaciones y conferencias de la industria para mantenerse actualizado con las últimas tendencias y tecnologías. Invertimos en tu desarrollo.",
		carreersWhatWeWelcomeTitle:"Lo que te ofrecemos",
		carreersExpertiseTitle:"Habilidad",
		carreersExpertiseText:"Valoramos las sólidas habilidades técnicas en áreas como desarrollo de software, ciberseguridad, computación en la nube y más. Muéstrenos su experiencia y capacidad para ofrecer resultados de alta calidad.",
		carreersProblemSolvingTitle:"Resolución de problemas",
		carreersProblemSolvingText:"Buscamos personas que se destaquen en el análisis y la resolución de problemas complejos. Su pensamiento crítico y sus soluciones innovadoras serán muy valoradas.",
		carreersTeamPlayerTitle:"Jugador de equipo",
		carreersTeamPlayerText:"La colaboración es clave. Queremos jugadores de equipo que aporten ideas y trabajen a la perfección con colegas y clientes para lograr objetivos comunes.",
		carreersAdaptabilityTitle:"Adaptabilidad",
		carreersAdaptabilityText:"La industria de TI evoluciona rápidamente, por lo que necesitamos profesionales que adopten el cambio y aprendan nuevas tecnologías con entusiasmo.",
		carreersStrongCommunicationTitle:"Comunicación fuerte",
		carreersStrongCommunicationText:"La comunicación efectiva es vital. Valoramos la articulación clara, la escucha activa y la capacidad de comunicar conceptos técnicos a audiencias diversas.",
		carreersClientFocusTitle:"Enfoque en el cliente",
		carreersClientFocusText:"La satisfacción de nuestros clientes es primordial. Buscamos personas que entiendan sus necesidades y estén comprometidas a brindar experiencias excepcionales.",
		carreersDriveExcellenceTitle:"Impuslados por la excelencia",
		carreersDriveExcellenceText:"Nos esforzamos por la excelencia. Si tiene una fuerte ética de trabajo, atención a los detalles y un deseo de mejorar continuamente, encajará perfectamente.",
		carreersEntrepreneurialMindsetTitle:"Mentalidad empresarial",
		carreersEntrepreneurialMindsetText:"Valoramos a las personas proactivas con mentalidad emprendedora. Si tiene recursos, asume la propiedad e impulsa el crecimiento empresarial, únase a nuestro equipo. Acepte los desafíos y tenga un impacto significativo en nuestro éxito.",
		carreersStrongerTogether:"Más fuertes juntos, logrando la grandeza como un solo equipo.",
		carreersDoYouHave:"¿Tienes algo mas para contribuir?",
		carreersLetsTalk:"Hablemos",
		// ABOUT US
		aboutTitle:"Nosotros",
		aboutOurMissionTitle:"Nuestra mision",
		aboutOurMissionText:"Nuestra misión en Tissen es empoderar a las empresas aprovechando el poder transformador de la tecnología. Nos esforzamos por ofrecer soluciones de TI de calidad que impulsen el éxito, ya sea a través del desarrollo de software innovador, la gestión eficiente de la infraestructura de TI o medidas sólidas de seguridad de datos. Al adherirnos a las mejores prácticas de la industria, utilizar las últimas tecnologías y trabajar en estrecha colaboración con nuestros clientes, obtenemos una comprensión profunda de sus objetivos y desafíos. Esto nos permite ofrecer soluciones a medida que hacen avanzar su negocio.",
		aboutOurMissionText2:"Tissen es una empresa líder en outsourcing de TI con sede en Argentina que atiende a clientes en todo el mundo. Con nuestro equipo de profesionales altamente calificados y expertos de la industria, nos enfocamos en brindar soluciones superiores de subcontratación para satisfacer las necesidades comerciales únicas de nuestros clientes. Nos distinguimos por un compromiso inquebrantable con la excelencia, la comunicación transparente y la construcción de asociaciones duraderas basadas en la confianza, la confiabilidad y el crecimiento mutuo.",
		aboutOurVisionTitle:"Nuestra vision",
		aboutOurVisionText:"Nuestra visión es ser la primera opción para las empresas que buscan un socio de outsourcing de TI confiable y competente. Nos esforzamos por ser reconocidos por nuestra experiencia, confiabilidad inquebrantable y compromiso inquebrantable con la satisfacción del cliente. Con una cartera diversa de proyectos exitosos en múltiples industrias, nos esforzamos por posicionarnos como asesores confiables que ayudan a las empresas a desarrollar todo su potencial a través de la tecnología. A través de nuestro compromiso inquebrantable y utilizando el excepcional grupo de talentos de Argentina, nuestro objetivo es ofrecer resultados excepcionales de manera constante, brindando a nuestros clientes una ventaja competitiva en sus mercados.",
		aboutEmpowering:"Empoderar la tecnología, apoyar a los usuarios",
		aboutLetsMeet:"Reunamonos",
		aboutWorkingTitle:"Personal de trabajo de Tissen",
		aboutWorkingText:"Con nuestros servicios de subcontratación de TI, puede reducir significativamente los costos mientras obtiene acceso a un equipo de profesionales calificados que se mantienen a la vanguardia de las últimas tendencias y mejores prácticas. Brindamos soporte las 24 horas, asegurando que sus sistemas funcionen sin problemas y abordando los problemas antes de que afecten sus operaciones.",
		aboutWorkingText2:"Nuestros servicios flexibles y escalables se adaptan a sus necesidades cambiantes y priorizamos la seguridad y el cumplimiento, protegiendo sus datos y cumpliendo con los estándares de la industria. Al asociarse con nosotros, puede concentrarse en sus objetivos comerciales principales mientras manejamos sus necesidades de TI.",

	},

	gr: {
		services: "Dienstleistungen",
		// what: "",
		how: "wie wir",
		carreers: "Karriere",
		about: "Über Uns",
		contact: "Kontaktieren Sie Uns",
		estimate: "Kostenvoranschlag für Ihr Projekt",
		save1: "Sparren Sie bis  zu ",
		save2: "30% ",
		save3: "der Ausgaben",
		project1: "Das Projekt startet garantiert in ",
		project2: "14 ",
		project3: "Tagen",
		technologies1: "Wir  benutzen die modernsten ",
		technologies2: "Technologien",
		tissenWay: "Tissen Way",
		innovativeSolutions1: "Fachwissen und ",
		innovativeSolutions2: "innovative Lösungen",
		personalizedApproach1: "Persönlicher Ansatz, ",
		personalizedApproach2: "der auf spezifische Anforderungen angepasst ist",
		successfulImplementations1: "Nachgewiesene Erfolgsbilanz ",
		successfulImplementations2: "erfolgreicher Implementierungen",
		comprehensivePortfolio1: "Umfassendes Portfolio an Dienstleistungen ",
		comprehensivePortfolio2: "für verschiedene technologische Anforderungen",
		customerRelationships1: "Verbraucherorientierter Ansatz und ",
		customerRelationships2: "starke Kundenbeziehungen",
		byServices: "Dienstleistungen",
		softwareDevelopment: "Softwareentwicklung",
		seguridadInformatica: "IT-Sicherheit",
		cloudHosting: "Cloud-Hosting",
		desarrolloWeb: "Web-Entwicklung ",
		desarrolloMobile: "App-Entwicklung",
		byTechnologie: "Technologien",
		IT_Outsourcing: "IT-Outsourcing bietet Kostensenkung, Zugang zu spezialisierten Fähigkeiten, Konzentration auf Kernkompetenzen, Skalierbarkeit, verbesserte Servicequalität und Risikominderung.	",
		whereAreWe: "Unsere Standorte",
		theTissen: "Das Unternehmen Tissen IT bietet Technologiedienstleistungen und -lösungen an und ist auf Softwareentwicklung und IT-Beratung spezialisiert. Wir beschäftigen qualifizierte Fachkräfte und bieten weltweit Outsourcing-Dienstleistungen an und tragen damit zum Wachstum der IT-Branche in Südamerika bei.	",
		southAmerica: "Sudamerica",
		GermanIT: "Ein deutsches IT-Unternehmen, das Unterstützung in den USA anbietet, ist auf eine breite Palette von Dienstleistungen spezialisiert.		. Mit ihrem technischen Know-how, ihrem innovativen Ansatz und ihrem interkulturellen Verständnis tragen sie zur Optimierung des IT-Betriebs bei.	",
		northAmerica: "Norteamerica",
		weAre: "Wir sind ein deutsches IT-Outsourcing-Unternehmen in Europa, das Unternehmen mit kostengünstigen und effizienten IT-Lösungen und -Dienstleistungen versorgt. Wir helfen Unternehmen, ihren IT-Betrieb zu rationalisieren und sich auf ihre Kernkompetenzen zu konzentrieren.	",
		europe: "Europa",
		// Footer
		footerServices: "Dienstleistungen",
		footerSoftware: "Softwareentwicklung",
		footerSecurity: "IT-Sicherheit",
		footerCloud: "Cloud-Hosting ",
		footerWeb: "Web-Development",
		footerMobile: "App-Development",
		footerTechnologies: "Technologien",
		footerCompany: "Unternehmen",
		footerAbout: "Über uns",
		footerCarrers: "Karriere",
		footerWhy: "",
		footerHow: "Wie wir",
		footerContact: "Kontakt",
		footerEmail: "Email",
		footerPhone: "Telefon",
		// Services
		servicesRouter: "Dienstleistungen",
		servicesSoftwareDevelopmentTitle: "Software Development",
		servicesSoftwareDevelopmentText: "Verwirklichen Sie Ihre Ideen mit unseren kundenspezifischen Softwareentwicklungsdiensten. Unsere Entwickler erstellen maßgeschneiderte Lösungen, die sich an Ihren Geschäftszielen orientieren und qualitativ hochwertigen Code und  Benutzererfahrung liefern.",
		servicesWebDevelpomentTitle: "Web Development",
		servicesWebDevelpomentText: "Schaffen Sie eine eindrucksvolle Webpräsenz mit unseren Webentwicklungsdiensten. Wir entwerfen und entwickeln visuell ansprechende und funktionale Websites, die Ihre Markenidentität widerspiegeln und die Konversionsrate erhöhen.",
		servicesMobileDevelopmentTitle: "Mobile Development",
		servicesMobileDevelopmentText: "Erreichen Sie Ihre Zielgruppe auf deren bevorzugten Geräten mit unseren mobilen Entwicklungsdiensten. Wir sind auf die Entwicklung intuitiver und funktionsreicher mobiler Anwendungen für iOS- und Android-Plattformen spezialisiert.",
		servicesNetworkSecuretyTitle: "Netzwerksicherheit",
		servicesNetworkSecuretyText: "Sorgen Sie mit unseren umfassenden Netzwerksicherheitsdiensten für die Sicherheit Ihrer Daten und Ihrer Netzwerkinfrastruktur. Wir bieten Risikobewertungen, Intrusion Detection, Firewall-Implementierung und laufende Überwachung, um Ihre wertvollen Informationen vor potenziellen Bedrohungen zu schützen.",
		servicesCloudHostingTitle: "Cloud Hosting",
		servicesCloudHostingText: "Erleben Sie die Vorteile eines flexiblen und zuverlässigen Cloud-Hostings. Unsere Experten führen Sie durch einen reibungslosen Migrationsprozess, optimieren die Leistung und reduzieren die Belastung durch die Verwaltung physischer Server.",
		servicesUXTitle: "UX/UI",
		servicesUXText: "Bieten Sie außergewöhnliche Benutzererlebnisse mit unseren UX/UI-Designservices. Unsere Designer kombinieren Ästhetik, Benutzerfreundlichkeit und Funktionalität, um Schnittstellen zu schaffen, die Benutzer ansprechen und die Kundenzufriedenheit steigern.",
		servicesWorkingProcessTitle: "Tissen Arbeitsverfahren",
		servicesRequermentsTitle: "Erfassen von Anforderungen",
		servicesRequermentsText: "Erfassen und Analysieren der Projektanforderungen, Verstehen der Ziele und Festlegen des Umfangs des Projekts.",
		servicesSystemDesignTitle: "Systementwurf",
		servicesSystemDesignText: "Erstellung eines detaillierten Systementwurfs, der die Architektur, die Komponenten und die Funktionalitäten der IT-Lösung umreißt.",
		servicesDevelopmentTitle: "Entwicklung",
		servicesDevelopmentText: "Schreiben des Codes und Implementieren des Systemdesigns unter Verwendung der gewählten Programmiersprachen, Frameworks und Tools.",
		servicesTestingTitle: "Testen",
		servicesTestingText: "Durchführung verschiedener Tests, z. B. Einheitstests, Integrationstests und Systemtests, zur Ermittlung und Behebung von Fehlern oder Problemen.",
		servicesDeploymentTitle: "Bereitstellung",
		servicesDeploymentText: "Bereitstellung der entwickelten Software oder des Systems in der Produktionsumgebung oder Bereitstellung für die Benutzer.",
		servicesMaintenenceTitle: "Wartung und Unterstützung",
		servicesMaintenenceText: "Laufende Wartung und Unterstützung für die entwickelte IT-Lösung, einschließlich Fehlerbehebungen, Aktualisierungen und Benutzerunterstützung.",
		servicesDocumentationTitle: "Dokumentation",
		servicesDocumentationText: "Dokumentieren des Systems, des Codes und der Benutzerhandbücher, um das richtige Verständnis, die Wartung und künftige Verbesserungen zu gewährleisten.",
		servicesContinuousTitle: "Kontinuierliche Verbesserung",
		servicesContinuousText: "Kontinuierliche Überwachung und Bewertung der Leistung der IT-Lösung, Einholen von Feedback und Vornahme von Verbesserungen zur Steigerung der Funktionalität und Effizienz.",
		servicesExcellenceInServiceTitle: "Hervorragender Service, der die Erwartungen jedes Mal übertrifft.",
		servicesLetsMeet:"termin vereinbaren",
		// HOW WE
		howTitle: "Wie Wir",
		howStepsTitle: "Schritte",
		howRequirementsGatheringTitle: "Erfassen der Anforderungen",
		howRequirementsGatheringText: "Erfassen und Analysieren der Projektanforderungen, Verstehen der Ziele und Festlegen des Umfangs des Projekts",
		howSystemDesignTitle: "System Design",
		howSystemDesignText: "Erstellung eines detaillierten Systementwurfs, der die Architektur, die Komponenten und die Funktionalitäten der IT-Lösung umreißt",
		howDevelopmentTitle: "Entwicklung",
		howDevelopmentText: "Schreiben des Codes und Implementieren des Systemdesigns unter Verwendung der gewählten Programmiersprachen, Frameworks und Tools",
		howTestingTitle: "Testen",
		howTestingText: "Durchführung verschiedener Tests, z. B. Einheitstests, Integrationstests und Systemtests, zur Ermittlung und Behebung von Fehlern oder Problemen",
		howDeploymentTitle: "Bereitstellung",
		howDeploymentText: "Bereitstellung der entwickelten Software oder des Systems in der Produktionsumgebung oder Bereitstellung für die Benutzer ",
		howMaintenanceSupportTitle: "Wartung und Unterstützung",
		howMaintenanceSupportText: "Laufende Wartung und Unterstützung für die entwickelte IT-Lösung, einschließlich Fehlerbehebungen, Aktualisierungen und Benutzerunterstützung",
		howDocumentationTitle: "Dokumentation",
		howDocumentationText: "Dokumentieren des Systems, des Codes und der Benutzerhandbücher, um das richtige Verständnis, die Wartung und künftige Verbesserungen zu gewährleisten ",
		howContinuousImprovementTitle: "Kontinuierliche Verbesserung",
		howContinuousImprovementText: "Kontinuierliche Überwachung und Bewertung der Leistung der IT-Lösung, Einholen von Feedback und Vornahme von Verbesserungen zur Steigerung der Funktionalität und Effizienz",
		howKnowUs: "Erfahren sie mehr",
		howAccording: "Laut einer Umfrage von Deloitte lagern etwa ",
		howAccording53: "53%",
		howOrganizations: " der Unternehmen weltweit ",
		howOutsource: "ihre IT-Funktionen ganz oder teilweise aus. ",
		howSourceDeloitte: "(Quelle: Deloitte Global Outsourcing Survey)",
		howInAddition: "Neben den technischen Fähigkeiten schätzen die Arbeitgeber bei IT-Fachkräften auch die Soft Skills. ",
		howCommunication: "Kommunikation, Problemlösung, Teamarbeit ",
		howAnd: "und ",
		howAdaptability: "Anpassungsfähigkeit ",
		howAmong: "gehören zu den wesentlichen Soft Skills, die von Arbeitgebern gesucht werden.",
		howAdvantagesTitle: "Vorteile",
		howCostSavingsTitle: "Kosteneinsparungen",
		howCostSavingsText: "Wir führen zu erheblichen Kosteneinsparungen für Unternehmen. Es entfällt die Notwendigkeit, internes IT-Personal einzustellen und zu schulen, in die Infrastruktur zu investieren und technologische Ressourcen zu pflegen. Offshore Outsourcing-Anbieter bieten oft flexible Preismodelle an, die es Unternehmen ermöglichen, für Dienstleistungen nach Bedarf zu zahlen.",
		howCoreBusinessTitle: "Kerngeschäft",
		howCoreBusinessText: "Die Auslagerung von IT-Aufgaben ermöglicht es Unternehmen, sich auf ihre Kernkompetenzen und strategischen Ziele zu konzentrieren. Indem sie IT-Aufgaben an externe Experten delegieren, können Unternehmen mehr Zeit und Ressourcen für Aktivitäten aufwenden, die direkt zu ihrem Wachstum und Wettbewerbsvorteil beitragen. ",
		howRiskManagementTitle: "Risikomanagement",
		howRiskManagementText: "Wir helfen dabei, die mit Technologieinvestitionen und -verwaltung verbundenen Risiken zu mindern. Outsourcing-Anbieter verfügen in der Regel über robuste Sicherheitsmaßnahmen, Notfallwiederherstellungspläne und Compliance-Rahmenwerke, die das Risiko von Datenschutzverletzungen, Systemausfällen oder der Nichteinhaltung von Vorschriften verringern.",
		howSpecializedSkillsTitle: "Spezialisierte Fertigkeiten und Fachwissen",
		howSpecializedSkillsText: "Tissen bietet Zugang zu einem Pool von hochqualifizierten Fachleuten mit spezialisiertem Fachwissen. Outsourcing-Anbieter verfügen oft über Teams von Fachleuten, die sich mit verschiedenen Technologien und bewährten Verfahren der Branche auskennen. So können Unternehmen das Wissen und die Fähigkeiten von Experten nutzen, ohne dass interne Schulungen oder Neueinstellungen erforderlich sind.",
		howScalabilityFlexibilityTitle: "Skalierbarkeit und Flexibilität",
		howScalabilityFlexibilityText: "Die Zusammenarbeit mit uns bietet Skalierbarkeit und Flexibilität, um veränderten Geschäftsanforderungen gerecht zu werden. Unternehmen können ihre IT-Ressourcen je nach Bedarf problemlos auf- oder abbauen, ohne dass umfangreiche Infrastrukturinvestitionen oder langfristige Verpflichtungen erforderlich sind.",
		howServiceLevelsTitle: "Service Levels",
		howServiceLevelsText: "Das Outsourcing von IT-Dienstleistungen geht oft mit definierten Service Level Agreements (SLAs) einher, die ein bestimmtes Maß an Leistung und Reaktionsfähigkeit garantieren. Die Anbieter konzentrieren sich darauf, diese SLAs zu erfüllen oder zu übertreffen, um einen effizienten und zuverlässigen IT-Betrieb für das Unternehmen zu gewährleisten. ",
		howThePrimaryText: "Zu den Hauptgründen, warum sich Unternehmen für die Auslagerung von IT-Funktionen entscheiden, ",
		howCostReduction: "gehören Kostensenkungen ",
		how64: "(64 %), ",
		howAccessing: "der Zugang zu spezialisierten Fähigkeiten ",
		how51: "(51 %), ",
		howImproving: "die bessere Konzentration auf das Kerngeschäft ",
		how46and: "(46 %) und ",
		howEnhancing: "die Verbesserung der Servicequalität ",
		how34Source: "(34 %). (Quelle: Deloitte Global Outsourcing Survey)",
		// CARREERS
		carreersJoinOurTeamTitle:"Werden Sie Teil unseres Teams",
		carreersJoinOurTeamText:"Sie sind technikbegeistert und auf der Suche nach spannenden Karrieremöglichkeiten? Wir bei Tissen sind ein führendes IT-Outsourcing-Unternehmen, das eine Reihe von lohnenden Aufgaben anbietet.",
		carreersWhyChooseUsTitle:"Warum uns wählen?",
		carreersDiverseProjectsTitle:"Vielfältige Projekte",
		carreersDiverseProjectsText:"Arbeiten Sie an einer Vielzahl von Projekten in verschiedenen Branchen, von innovativen Softwarelösungen bis hin zu groß angelegten Infrastrukturimplementierungen. Verbessern Sie Ihre Fähigkeiten und Ihr Fachwissen durch vielfältige Herausforderungen.",
		carreersCompetitiveCompensationTitle:"Wettbewerbsfähige Entlohnung",
		carreersCompetitiveCompensationText:"Als Anerkennung für Ihre harte Arbeit und Ihr Engagement erhalten Sie wettbewerbsfähige Gehälter und umfassende Sozialleistungen.",
		carreersWorkLifeBalanceTitle:"Work-Life Balance",
		carreersWorkLifeBalanceText:"Wir bieten flexible Arbeitszeiten und die Möglichkeit der Fernarbeit, um ein ausgewogenes Verhältnis zwischen Arbeit und Privatleben zu gewährleisten.",
		carreersCollaborativeEnvironmentTitle:"Kollaboratives Umfeld",
		carreersCollaborativeEnvironmentText:"Schließen Sie sich talentierten Fachleuten an, die Wert auf Teamarbeit, Wissensaustausch und eine integrative Arbeitskultur legen, die Kreativität und Innovation begünstigt.",
		carreersContinuousLearningTitle:"Kontinuierliches Lernen",
		carreersContinuousLearningText:"Nutzen Sie Schulungsprogramme, Zertifizierungen und Branchenkonferenzen, um sich über die neuesten Trends und Technologien auf dem Laufenden zu halten. Wir investieren in Ihre Entwicklung.",
		carreersWhatWeWelcomeTitle:"Was wir begrüßen",
		carreersExpertiseTitle:"Fachwissen",
		carreersExpertiseText:"Wir schätzen starke technische Fähigkeiten in Bereichen wie Softwareentwicklung, Cybersicherheit, Cloud Computing und mehr. Zeigen Sie uns Ihr Fachwissen und Ihre Fähigkeit, hochwertige Ergebnisse zu liefern.",
		carreersProblemSolvingTitle:"Problemlösung",
		carreersProblemSolvingText:"Wir suchen Personen, die sich durch die Analyse und Lösung komplexer Probleme auszeichnen. Ihr kritisches Denken und Ihre innovativen Lösungen werden von uns sehr geschätzt.",
		carreersTeamPlayerTitle:"Team Player",
		carreersTeamPlayerText:"Zusammenarbeit ist der Schlüssel. Wir wollen Teamplayer, die Ideen einbringen und mit Kollegen und Kunden zusammenarbeiten, um gemeinsame Ziele zu erreichen.",
		carreersAdaptabilityTitle:"Anpassungsfähigkeit",
		carreersAdaptabilityText:"Die IT-Branche entwickelt sich rasant, daher brauchen wir Fachleute, die sich auf Veränderungen einlassen und eifrig neue Technologien erlernen.",
		carreersStrongCommunicationTitle:"Starke Kommunikation",
		carreersStrongCommunicationText:"Wirksame Kommunikation ist entscheidend. Wir legen Wert auf eine klare Ausdrucksweise, aktives Zuhören und die Fähigkeit, technische Konzepte an unterschiedliche Zielgruppen zu vermitteln.",
		carreersClientFocusTitle:"Kundenfokus",
		carreersClientFocusText:"Die Zufriedenheit unserer Kunden steht an erster Stelle. Wir suchen Menschen, die ihre Bedürfnisse verstehen und sich dafür einsetzen, außergewöhnliche Erfahrungen zu machen.",
		carreersDriveExcellenceTitle:"Streben nach Exzellenz",
		carreersDriveExcellenceText:"Wir streben nach Spitzenleistungen. Wenn Sie eine hohe Arbeitsmoral, Liebe zum Detail und den Wunsch haben, sich ständig zu verbessern, dann sind Sie genau der Richtige für uns.",
		carreersEntrepreneurialMindsetTitle:"Unternehmerische Denkweise",
		carreersEntrepreneurialMindsetText:"Wir schätzen proaktive Personen mit einer unternehmerischen Denkweise. Wenn Sie einfallsreich sind, Verantwortung übernehmen und das Unternehmenswachstum vorantreiben, sollten Sie sich unserem Team anschließen. Nehmen Sie Herausforderungen an und tragen Sie maßgeblich zu unserem Erfolg bei.",
		carreersStrongerTogether:"Gemeinsam stärker, als ein Team Großes erreichen.",
		carreersDoYouHave:"Haben wir Ihr Interesse geweckt?",
		carreersLetsTalk:"Termin vereinbaren",
		// ABOUT US
		aboutTitle:"Über Uns",
		aboutOurMissionTitle:"Unsere Mission",
		aboutOurMissionText:"Unsere Aufgabe bei Tissen ist es, Unternehmen durch die Nutzung der transformativen Kraft der Technologie zu unterstützen. Wir streben danach, hochwertige IT-Lösungen zu liefern, die den Erfolg fördern, sei es durch innovative Softwareentwicklung, effizientes IT-Infrastrukturmanagement oder starke Datensicherheitsmaßnahmen. Durch die Einhaltung von Best Practices in der Branche, den Einsatz neuester Technologien und die enge Zusammenarbeit mit unseren Kunden gewinnen wir ein tiefes Verständnis für deren Ziele und Herausforderungen. So können wir maßgeschneiderte Lösungen anbieten, die Ihr Unternehmen voranbringen.",
		aboutOurMissionText2:"Tissen ist ein führendes IT-Outsourcing-Unternehmen mit Hauptsitz in Argentinien, das Kunden auf der ganzen Welt betreut. Mit unserem Team aus hochqualifizierten Fachleuten und Branchenexperten konzentrieren wir uns auf die Bereitstellung erstklassiger Outsourcing-Lösungen, um die einzigartigen Geschäftsanforderungen unserer Kunden zu erfüllen. Wir zeichnen uns durch unser Engagement für hervorragende Leistungen, transparente Kommunikation und den Aufbau dauerhafter Partnerschaften aus, die auf Vertrauen, Zuverlässigkeit und gegenseitigem Wachstum basieren.",
		aboutOurVisionTitle:"Unsere Vision",
		aboutOurVisionText:"Unsere Vision ist es, die erste Wahl für Unternehmen zu sein, die einen zuverlässigen und kompetenten IT-Outsourcing-Partner suchen. Wir streben danach, für unser Fachwissen, unsere unerschütterliche Zuverlässigkeit und unser unermüdliches Engagement für die Zufriedenheit unserer Kunden anerkannt zu werden. Mit einem breit gefächerten Portfolio erfolgreicher Projekte in verschiedenen Branchen wollen wir uns als vertrauenswürdiger Berater positionieren, der Unternehmen dabei hilft, ihr volles Potenzial durch Technologie auszuschöpfen. Durch unser unermüdliches Engagement und die Nutzung des außergewöhnlichen argentinischen Talentpools wollen wir beständig außergewöhnliche Ergebnisse liefern, die unseren Kunden einen Wettbewerbsvorteil auf ihren Märkten verschaffen.",
		aboutEmpowering:"Technologie befähigen, Anwender unterstützen",
		aboutLetsMeet:"Termin vereinbaren",
		aboutWorkingTitle:"Tissen Working Staff",
		aboutWorkingText:"Mit unseren IT-Outsourcing-Diensten können Sie Ihre Kosten erheblich senken und Sie erhalten gleichzeitig Zugang zu einem Team von qualifizierten Fachleuten, die den neuesten Trends und bewährten Verfahren immer einen Schritt voraus sind. Wir unterstützen Sie rund um die Uhr und sorgen dafür, dass Ihre Systeme reibungslos laufen und Probleme behoben werden, bevor sie sich auf Ihren Betrieb auswirken.",
		aboutWorkingText2:"Unsere flexiblen und skalierbaren Dienste passen sich an Ihre sich entwickelnde Bedürfnisse an. Wir legen Wert auf Sicherheit und Compliance, um Ihre Daten zu schützen und Branchenstandards zu erfüllen. Wenn Sie mit uns zusammenarbeiten, können Sie sich auf Ihre eigentlichen Geschäftsziele konzentrieren, während wir uns um Ihre IT-Anforderungen kümmern.",


	}
}

export default trans