const trans = {
	en: {
		services: "Services",
		what: "What we",
		how: "How we",
		carreers: "carreers",
		about: "about us",
		contact: "contact us",
		estimate: "estimate your project",
		save1: "save up to ",
		save2: "30%",
		save3: "of your cost.",
		project1: "project starts at",
		project2: "14",
		project3: "days guarenteed.",
		technologies1: "with the best",
		technologies2: "technologies.",
		tissenWay: "Tissen Way",
		innovativeSolutions1: "Expertise and ",
		innovativeSolutions2: "innovative solutions.",
		personalizedApproach1: "Personalized approach ",
		personalizedApproach2: "tailored to specific needs.",
		successfulImplementations1: "Proven track record of ",
		successfulImplementations2: "successful implementations.",
		comprehensivePortfolio1: "Comprehensive portfolio ",
		comprehensivePortfolio2: "of services for various technological needs.",
		customerRelationships1: "Consumer-centric approach and ",
		customerRelationships2: "strong customer relationships.",
		byServices: "By Services",
		softwareDevelopment: "Software Development",
		seguridadInformatica: "Network Security",
		cloudHosting: "Cloud Hosting",
		desarrolloWeb: "Web Development ",
		desarrolloMobile: "Mobile Develompent",
		byTechnologie: "By Technologie",
		IT_Outsourcing: "IT outsourcing offers cost reduction, access to specialized skills, focus on core competencies, scalability, improved service levels and risk mitigation.",
		whereAreWe: "Where are we",
		theTissen: "The Tissen IT company provides technology services and solutions, specializing in software development and IT consulting. We employ qualified professionals and offer outsourcing services globally, contributing to the growth of the IT industry in South America.",
		southAmerica: "South America",
		GermanIT: "A German IT company providing assistance in the USA specializes in delivering a wide range of IT services and solutions tailored to meet the specific needs of American businesses. With its technical expertise, innovative approach, and cross-cultural understanding, it helps optimize IT operations.",
		northAmerica: "North America",
		weAre: "We are a German IT outsourcing company in Europe providing businesses with cost-effective and efficient IT solutions and services. We help companies streamline their IT operations while allowing them to focus on their core competencies.",
		europe: "Europe",
		// Footer
		footerServices: "Services",
		footerSoftware: "Software Development",
		footerSecurity: "Network Security",
		footerCloud: "Cloud Hosting ",
		footerWeb: "Web Development",
		footerMobile: "Mobile Development",
		footerTechnologies: "Technologies",
		footerCompany: "Company",
		footerAbout: "About us",
		footerCarrers: "Carrers",
		footerWhy: "Why us",
		footerHow: "How us ",
		footerContact: "Contact us",
		footerEmail: "Email",
		footerPhone: "Phones",
		// Services
		servicesRouter: "Services",
		servicesSoftwareDevelopmentTitle:"Software Development",
		servicesSoftwareDevelopmentText:"Transform your ideas into reality with our custom software development services. Our expert developers will create tailored solutions that align with your business goals, delivering high-quality code and seamless user experiences.",
		servicesWebDevelpomentTitle:"Web Development",
		servicesWebDevelpomentText:"Transform your ideas into reality with our custom software development services. Our expert developers will create tailored solutions that align with your business goals, delivering high-quality code and seamless user experiences.",
		servicesMobileDevelopmentTitle:"Mobile Development",
		servicesMobileDevelopmentText:"Reach your target audience on their preferred devices with our mobile development services. We specialize in building intuitive and feature-rich mobile applications for both iOS and Android platforms.",
		servicesNetworkSecuretyTitle:"Network Security",
		servicesNetworkSecuretyText:"Ensure the safety of your data and network infrastructure with our comprehensive network security services. We offer risk assessments, intrusion detection, firewall implementation, and ongoing monitoring to protect your valuable information from potential threats.",
		servicesCloudHostingTitle:"Cloud Hosting",
		servicesCloudHostingText:"Experience the benefits of flexible and reliable cloud hosting. Our experts will guide you through a seamless migration process, optimizing performance and reducing the burden of managing physical servers.",
		servicesUXTitle:"UX/UI",
		servicesUXText:"Deliver exceptional user experiences with our UX/UI design services. Our designers combine aesthetics, usability, and functionality to create interfaces that engage users and drive customer satisfaction.",
		servicesWorkingProcessTitle:"Tissen Working Process",
		servicesRequermentsTitle:"Requirements Gathering",
		servicesRequermentsText:"Gathering and analyzing the project requirements, understanding the objectives, and defining the scope of the project.",
		servicesSystemDesignTitle:"System Design",
		servicesSystemDesignText:"Creating a detailed system design that outlines the architecture, components, and functionalities of the IT solution.",
		servicesDevelopmentTitle:"Development",
		servicesDevelopmentText:"Writing the code and implementing the system design, using the chosen programming languages, frameworks, and tools.",
		servicesTestingTitle:"Testing",
		servicesTestingText:"Conducting various testing activities, such as unit testing, integration testing, and system testing, to identify and fix any bugs or issues.",
		servicesDeploymentTitle:"Deployment",
		servicesDeploymentText:"Deploying the developed software or system to the production environment or making it available to users.",
		servicesMaintenenceTitle:"Maintenance and Support",
		servicesMaintenenceText:"Providing ongoing maintenance and support for the developed IT solution, including bug fixes, updates, and user assistance.",
		servicesDocumentationTitle:"Documentation",
		servicesDocumentationText:"Documenting the system, code, and user manuals to ensure proper understanding, maintenance, and future enhancements.",
		servicesContinuousTitle:"Continuous Improvement",
		servicesContinuousText:"Continuously monitoring and evaluating the IT solution's performance, gathering feedback, and making improvements to enhance its functionality and efficiency.",
		servicesExcellenceInServiceTitle:"Excellence in service, exceeding expectations every time.",



	},
	es: {
		services: "Servicios",
		what: "Que hacemos",
		how: "Como lo hacemos",
		carreers: "Unite",
		about: "nosotros",
		contact: "Contactanos",
		estimate: "Estima tu proyecto",
		save1: "Ahorra hasta un",
		save2: " 30%.",
		save3: "",
		project1: "Proyecto empieza en",
		project2: "14",
		project3: "dias garantizado.",
		technologies1: "Con la mejor",
		technologies2: "Tecnologia",
		tissenWay: "Tissen estilo",
		innovativeSolutions1: "Pericia y ",
		innovativeSolutions2: "soluciones innovadoras.",
		personalizedApproach1: "Enfoque personalizado",
		personalizedApproach2: "adaptado a las necesidades específicas.",
		successfulImplementations1: "Historial comprobado de ",
		successfulImplementations2: "implementaciones exitosas.",
		comprehensivePortfolio1: "Portafolio integral de servicios ",
		comprehensivePortfolio2: "para diversas necesidades tecnológicas.",
		customerRelationships1: "Enfoque centrado en el consumidor y ",
		customerRelationships2: "relaciones sólidas con los clientes.",
		byServices: "Por Servicio",
		softwareDevelopment: "Desarrollo Software ",
		seguridadInformatica: "Seguridad Informatica",
		cloudHosting: "Cloud Hosting",
		desarrolloWeb: "Desarrollo Web ",
		desarrolloMobile: "Desarrollo Mobile",
		byTechnologie: "Por Tecnologia",
		IT_Outsourcing: "La tercerizacion de TI ofrece disminución de costos, acceso a habilidades especializadas, enfoque en competencias básicas, escalabilidad, niveles de servicio mejorados y mitigación de riesgos.",
		whereAreWe: "Donde Estamos",
		theTissen: "La empresa Tissen IT brinda servicios y soluciones de tecnología, especializándose en desarrollo de software y consultoría de TI. Emplean a profesionales calificados y ofrecen servicios de tercerización a nivel mundial, lo que contribuye al crecimiento de la industria de TI en América del Sur.",
		southAmerica: "Sudamerica",
		GermanIT: "Una empresa alemana de TI que brinda asistencia en los EE. UU. se especializa en brindar una amplia gama de servicio. Con su experiencia técnica, enfoque innovador y comprensión intercultural, ayudan a optimizar las operaciones de TI",
		northAmerica: "Norteamerica",
		weAre: "Somos una empresa alemana de subcontratación de TI en Europa que brinda a las empresas servicios y soluciones de TI rentables y eficientes. ayudamos a las empresas a optimizar sus operaciones de TI mientras les permitimos concentrarse en sus competencias principales.",
		europe: "Europa",
		// Footer
		footerServices: "Servicios",
		footerSoftware: "Desarrollo de Software",
		footerSecurity: "Seguridad informatica",
		footerCloud: "Cloud Hosting ",
		footerWeb: "Desarrollo Web",
		footerMobile: "Desarrollo Mobile",
		footerTechnologies: "Tecnologias",
		footerCompany: "Compania",
		footerAbout: "Sobre nosotros",
		footerCarrers: "Unite",
		footerWhy: "Porque Tissen",
		footerHow: "Como Tissen",
		footerContact: "Contactanos",
		footerEmail: "Mail",
		footerPhone: "Telefonos",
		// Services
		servicesRouter: "Servicios",
		servicesSoftwareDevelopmentTitle:"",
		servicesSoftwareDevelopmentText:"",
		servicesWebDevelpomentTitle:"",
		servicesWebDevelpomentText:"",
		servicesMobileDevelopmentTitle:"",
		servicesMobileDevelopmentText:"",
		servicesNetworkSecuretyTitle:"",
		servicesNetworkSecuretyText:"",
		servicesCloudHostingTitle:"",
		servicesCloudHostingText:"",
		servicesUXTitle:"",
		servicesUXText:"",
		servicesWorkingProcessTitle:"",
		servicesRequermentsTitle:"",
		servicesRequermentsText:"",
		servicesSystemDesignTitle:"",
		servicesSystemDesignText:"",
		servicesDevelopmentTitle:"",
		servicesDevelopmentText:"",
		servicesTestingTitle:"",
		servicesTestingText:"",
		servicesDeploymentTitle:"",
		servicesDeploymentText:"",
		servicesMaintenenceTitle:"",
		servicesMaintenenceText:"",
		servicesDocumentationTitle:"",
		servicesDocumentationText:"",
		servicesContinuousTitle:"",
		servicesContinuousText:"",
		servicesExcellenceInServiceTitle:"",

	},

	gr: {
		services: "Dienstleistungen",
		what: "",
		how: "wie wir",
		carreers: "Karriere",
		about: "Über Uns",
		contact: "Kontaktieren Sie Uns",
		estimate: "Kostenvoranschlag für Ihr Projekt",
		save1: "Sparren Sie bis  zu ",
		save2: "30% ",
		save3: "der Ausgaben",
		project1: "Das Projekt startet garantiert in ",
		project2: "14 ",
		project3: "Tagen",
		technologies1: "Wir  benutzen die modernsten ",
		technologies2: "Technologien",
		tissenWay: "Tissen Way",
		innovativeSolutions1: "Fachwissen und ",
		innovativeSolutions2: "innovative Lösungen",
		personalizedApproach1: "Persönlicher Ansatz, ",
		personalizedApproach2: "der auf spezifische Anforderungen angepasst ist",
		successfulImplementations1: "Nachgewiesene Erfolgsbilanz ",
		successfulImplementations2: "erfolgreicher Implementierungen",
		comprehensivePortfolio1: "Umfassendes Portfolio an Dienstleistungen ",
		comprehensivePortfolio2: "für verschiedene technologische Anforderungen",
		customerRelationships1: "Verbraucherorientierter Ansatz und ",
		customerRelationships2: "starke Kundenbeziehungen",
		byServices: "Dienstleistungen",
		softwareDevelopment: "Softwareentwicklung",
		seguridadInformatica: "IT-Sicherheit",
		cloudHosting: "Cloud-Hosting",
		desarrolloWeb: "Web-Entwicklung ",
		desarrolloMobile: "App-Entwicklung",
		byTechnologie: "Technologien",
		IT_Outsourcing: "IT-Outsourcing bietet Kostensenkung, Zugang zu spezialisierten Fähigkeiten, Konzentration auf Kernkompetenzen, Skalierbarkeit, verbesserte Servicequalität und Risikominderung.	",
		whereAreWe: "Unsere Standorte",
		theTissen: "Das Unternehmen Tissen IT bietet Technologiedienstleistungen und -lösungen an und ist auf Softwareentwicklung und IT-Beratung spezialisiert. Wir beschäftigen qualifizierte Fachkräfte und bieten weltweit Outsourcing-Dienstleistungen an und tragen damit zum Wachstum der IT-Branche in Südamerika bei.	",
		southAmerica: "Sudamerica",
		GermanIT: "Ein deutsches IT-Unternehmen, das Unterstützung in den USA anbietet, ist auf eine breite Palette von Dienstleistungen spezialisiert.		. Mit ihrem technischen Know-how, ihrem innovativen Ansatz und ihrem interkulturellen Verständnis tragen sie zur Optimierung des IT-Betriebs bei.	",
		northAmerica: "Norteamerica",
		weAre: "Wir sind ein deutsches IT-Outsourcing-Unternehmen in Europa, das Unternehmen mit kostengünstigen und effizienten IT-Lösungen und -Dienstleistungen versorgt. Wir helfen Unternehmen, ihren IT-Betrieb zu rationalisieren und sich auf ihre Kernkompetenzen zu konzentrieren.	",
		europe: "Europa",
		// Footer
		footerServices: "Dienstleistungen",
		footerSoftware: "Softwareentwicklung",
		footerSecurity: "IT-Sicherheit",
		footerCloud: "Cloud-Hosting ",
		footerWeb: "Web-Development",
		footerMobile: "App-Development",
		footerTechnologies: "Technologien",
		footerCompany: "Unternehmen",
		footerAbout: "Über uns",
		footerCarrers: "Karriere",
		footerWhy: "",
		footerHow: "Wie wir",
		footerContact: "Kontakt",
		footerEmail: "Email",
		footerPhone: "Telefon",
		// Services
		servicesRouter: "Dienstleistungen",
		servicesSoftwareDevelopmentTitle:"",
		servicesSoftwareDevelopmentText:"",
		servicesWebDevelpomentTitle:"",
		servicesWebDevelpomentText:"",
		servicesMobileDevelopmentTitle:"",
		servicesMobileDevelopmentText:"",
		servicesNetworkSecuretyTitle:"",
		servicesNetworkSecuretyText:"",
		servicesCloudHostingTitle:"",
		servicesCloudHostingText:"",
		servicesUXTitle:"",
		servicesUXText:"",
		servicesWorkingProcessTitle:"",
		servicesRequermentsTitle:"",
		servicesRequermentsText:"",
		servicesSystemDesignTitle:"",
		servicesSystemDesignText:"",
		servicesDevelopmentTitle:"",
		servicesDevelopmentText:"",
		servicesTestingTitle:"",
		servicesTestingText:"",
		servicesDeploymentTitle:"",
		servicesDeploymentText:"",
		servicesMaintenenceTitle:"",
		servicesMaintenenceText:"",
		servicesDocumentationTitle:"",
		servicesDocumentationText:"",
		servicesContinuousTitle:"",
		servicesContinuousText:"",
		servicesExcellenceInServiceTitle:"",

	}
}

export default trans